### ISSUE TITLE
lorawan - STM32 + SX1276 (WISOL)

### ISSUE THREAD

**Issue by tcpipchip** [RT-Thread/community-activities#90]
Sir

How are you ?

Let's port your example to the WISOL LOM204 MODULE ?

uses a stm32L071 + SX1276

**Comment by mysterywolf** [comment]
https://packages.rt-thread.org/en/detail.html?package=sx12xx
we have a sx12xx software pacakge

**Comment by tcpipchip** [comment]
hi @mysterywolf 
will work with SX1276 ?

**Comment by mysterywolf** [comment]
according the tag, Yes
![image](https://user-images.githubusercontent.com/34888354/149212448-16816e34-659a-4ebc-8d56-9a5731ca8b65.png)
https://github.com/XiaojieFan/sx12xx

**Comment by tcpipchip** [comment]
do you remember on RT-THREAD how to import/open that project ?

**Comment by mysterywolf** [comment]
https://www.rt-thread.io/document/site/programming-manual/env/env/
https://www.youtube.com/watch?v=dEK94o_YoSo&list=PLXUV89C_M3G4ltgbiC6wWBhjREXEjFEBu
https://www.youtube.com/watch?v=hzYazxqEHUI&list=PLXUV89C_M3G5KVw2IerI-pqApdSM_IaZo&index=2
https://www.youtube.com/watch?v=k4-ArvvIiR8&list=PLXUV89C_M3G5KVw2IerI-pqApdSM_IaZo&index=3
https://www.youtube.com/watch?v=F_kU1CMjLKw&list=PLXUV89C_M3G5KVw2IerI-pqApdSM_IaZo&index=4
Please take a look at this information

**Comment by tcpipchip** [comment]
thank you @mysterywolf

**Comment by tcpipchip** [comment]
Looks that not works to SX1276 until the moment

**Comment by tcpipchip** [comment]
Hi, i am back!

Can you help me to build a LoRaWAN example to SX1276+STM32L073 on RT-THREAD ?
Our Region in AU915.
I want to run on LOM204A
